### ISSUE TITLE
Add an ability to update only a single directory in the library

### ISSUE THREAD

**Issue by p-himik** [pragha-music-player/pragha#155]
At least in my usage of the player, it's pretty often that I change only a single directory. Running "Update library" after that can take quite some time. I think making it possible to have a "Update directory in the library" item in the library directories' context menu would make sense.

**Comment by matiasdelellis** [comment]
Hi @p-himik 
I thought I had answered this report. Excuse me.
I will not add an option to 'update a directory', since it would add more confusing options. (There are reports of people who don't like to have the 'update library' and 'update library completely' options)

In any case, what we must do is improve the performance of the update.

**Comment by p-himik** [comment]
I can see how "Update library" and "Update library completely" is confusing. But I fail to see the same for "Update library" in "Update the selected directory" that's active only in the context menu.
But it should be fine if the indexing becomes so fast indeed so that it doesn't really matter what part of the library you index.
