### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by manuel-uberti** [pragha-music-player/pragha#89]
Does Pragha support gapless playback?

I'm not able to play mp3s gapless, at least not in the same way DeaDBeeF automatically does.

I'm on Debian Sid, using Pragha installed from here: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/pragha

Do I have to  set some config in particular?

**Comment by rat4** [comment]
There was an attempt to implement this feature: https://github.com/pragha-music-player/pragha/pull/36

**Comment by manuel-uberti** [comment]
Any news on that? Because as of today there is no gapless playback.

**Comment by matiasdelellis** [comment]
Hi @manuel-uberti 

> Does Pragha support gapless playback?

Currently not.... :disappointed: 

> There was an attempt to implement this feature: #36

Continues on plan, but beyond the pull request #36 (Closed by the same author ..), there is no attempt to do it..

Also, a note about it .. The use of the about-to-finish signal of playbin not ensure the full gapless. If your audio file containing five seconds at the end of the song, will play to the end of the file, breaking any concept of gapless. .
The only thing that does this signal is to ensure that when finished the song, you already decided which is the next song to play. Saving only 50ms of time.. :cry: 

Sorry. Surely this is not the support you waiting, and for this reason is that still neither was implemented by me.

**Comment by manuel-uberti** [comment]
Ok, thanks for the explanation. We can close this issue now.
